### ISSUE TITLE
WP Multisite and custom shortlink base url

### ISSUE THREAD

**Issue by chrisbergr** [willnorris/wordpress-hum#20]
Hi Will,
I figured out the following:

1. **demo.example.com (Page of a wp multisite network)
exm.pl (redirects everything to demo.example.com via htaccess)**
With this setup, I'll get the short link "exm.pl/p/G" on my blog post "demo.example.com/test". That looks fine, but because of the htaccess file, I got redirected to "demo.example.com/p/G" without any further action from hum and an error message 404 after calling the short URL in the browser.
2. **demo.example.com (Page of a wp multisite network)
exm.pl (points to the same folder on the server like demo.example.com via vhosts)**
After calling the short URL in the browser I got a wp multisite error displayed, saying that my registrations are disabled. Seems like the multisite is trying to handle the domain as one of its subpages.

I think there are two possible solutions for this:

1. Add setting for custom short link base URL to multisite network admin page, where the options for the sites are. According to this, there is some magic required that the network knows what to do with this specific URL. Maybe some setting like "alias" for sites.
2. Add a second options field to the general settings page right below the current shortlink base URL field. Call it "Shortlink Alias" or "Output Base URL). 
This leaves the "real" base URL as default, but get's in use every time the shortlink get's printed out on the frontend. With this configuration, I can use my first setup described above and everything will work, because hum knows how to handle "demo.example.com/p/G".

While writing this, I belive the second solutions need less effort and can be done in a quick amount of time. There would be one additional redirect, but I'd be fine with this if I can use it for my multisite purpose.

Maybe there is one more usecase:
Someone may like to link the shortlink exm.pl tho the whole network, like  "demo.exm.pl/p/G" linking to "demo.example.com/test", but this is not my case here.

Please let me know your thoughts

**Comment by chrisbergr** [comment]
I just realized that hum isn't able to use "demo.example.com/p/G" on multisite, even without defined shortlink base URL.

**Comment by pfefferle** [comment]
Can you try to hit „save“ on the permalinks page to regenerate the rewriting rules and then try it again?

**Comment by pfefferle** [comment]
Might be a duplicate of https://github.com/willnorris/wordpress-hum/issues/11

**Comment by chrisbergr** [comment]
Yes, regenerating the rewrite rules fixed it with my first described setup. Now everything works as expected for my multisite and this topic is obsolete.

**Comment by chrisbergr** [comment]
Just to confirm: The second setup (short url pointing to multisite root domain) also works after regenerating the rewrite rules.

**Comment by pfefferle** [comment]
👍 

so can we close this?

**Comment by chrisbergr** [comment]
Yes.
