### ISSUE TITLE
No instructions make it hard to use

### ISSUE THREAD

**Issue by cristian-milea** [willnorris/wordpress-hum#23]
I don't understand how to use this plugin. Does it have a menu on the left? does it generate automatically? Please add some instructions because I installed but have no clue on how to use..

**Comment by willnorris** [comment]
Cristi, see if the updated docs are sufficient, or if you think more is needed.

**Comment by pfefferle** [comment]
@cristian-milea The latest version show the shortlink on the post/page overview pages and I am also working on a Gutenberg/Block-Editor integration. But therefore I have to learn how Gutenberg works ;)

**Comment by pfefferle** [comment]
@cristian-milea The gutenberg integration is now already done, so I close this issue... Feel free to re-open if you still need something.
