### ISSUE TITLE
display shortlink in WordPress edit screen

### ISSUE THREAD

**Issue by willnorris** [willnorris/wordpress-hum#25]
I don't know how to extend Gutenberg edit pages, so this will require a little bit of investigation.  But it seems reasonable to try and surface the shortlink for a page/post somewhere in the edit screen.

**Comment by willnorris** [comment]
Just for comparison, Jetpack adds this to their own custom editor sidebar:

![image](https://user-images.githubusercontent.com/1112/83917986-ac56f100-a72c-11ea-8ab1-b1bd502267e0.png)

We don't have a custom sidebar, now should we add one just for this, so we'd need to figure out some other place to add it.

**Comment by willnorris** [comment]
That feels maybe *too* prominent?  What about in the links that appear on hover:

<img width="728" alt="Screen Shot 2020-06-10 at 5 17 34 PM" src="https://user-images.githubusercontent.com/1112/84331213-7a83c700-ab3e-11ea-805c-2af3f9f02550.png">

**Comment by pfefferle** [comment]
The problem with the link list is, that it is too long to show the complete URL and it does not help if we link to it, because it directly redirects?!?

If it is too prominent in the list, you can simply deactivate it using the settings button on the top right.

**Comment by willnorris** [comment]
I wasn't thinking we would show the whole URL, just link to it with the word "shortlink", and people could right click and copy the URL.  But I had also forgotten that WordPress lets you turn columns on and off, so the column totally works for me.

**Comment by pfefferle** [comment]
Ah, I see. I can prepare a MR so we have something to discuss

**Comment by pfefferle** [comment]
Added by #30
