### ISSUE TITLE
When Hum Plugin is On Strange Redirects Occur

### ISSUE THREAD

**Issue by dshanske** [willnorris/wordpress-hum#32]
On my site, if Hum is enabled, then putting in /1998, which has no posts and should give me an empty archive, redirects me to post ID 1998. It should 404.

**Comment by dshanske** [comment]
It appears to be the legacy redirect template function introduced as part of the #6 discussion. Is there a way to determine the request is made via the shortlink versus the full site URL?

**Comment by dshanske** [comment]
I've temporarily unhooked the redirect, but would like to see if there is a better way.

**Comment by dshanske** [comment]
The reason I noticed this was because I have been working on adding to my theme, if you request a date based archive that isn't there, it would show you navigation for the nearest available dates, as opposed to requesting a post or page URL that isn't there, where it wouldn't. I spent a bit of time before figuring out it was Hum doing this.

**Comment by willnorris** [comment]
I don't really know of a better way than what you describe... just unhooking the legacy redirect.  Or overriding it with:

``` php
add_filter( 'hum_legacy_id', '__return_false', 99 );
```

And if you're not using those legacy redirects, that certainly seems like the Right Way to do it.

Off the top of my head, there's not a super easy way to differentiate between a short URL request and regular page request.  Maybe include an extra query parameter in the short URL redirect that you then check for?  But that's a lot messier than just disabling the legacy redirects.

**Comment by dshanske** [comment]
For now, I think that's the key. Although maybe a config flag is easier than adding to the filter. The question is whether legacy redirects should be on by default or off.

**Comment by willnorris** [comment]
In the 8 years or so that this has been in the plugin, this is the first I've heard of it causing any problems, so 🤷🏻 .  But at the same time, I can't possibly imagine that too many people are migrating from other systems and would even have these legacy URLs, so I'd be fine disabling it and just documenting how to turn it on.

**Comment by dshanske** [comment]
Maybe I'll submit a PR
