### ISSUE TITLE
Created shortlink ends in 404 not found for a certain post

### ISSUE THREAD

**Issue by bekopharm** [willnorris/wordpress-hum#33]
Today I posted a note and got `/x/N505` as shortlink for `/2022/05/12/4770005/`

This is answered with a 404 error: `GET /x/N505 HTTP/1.1" 404` by WordPress.

I added a manual redirect in my nginx config now to make this one fly.
 
I've a lot of other/older shortlinks working just fine.

PHP version is 8.0
WordPress version is 5.9.3
Hum version is 1.2.8

**Comment by pfefferle** [comment]
Have you written some kind of extension? I am not aware that `/x` is a supported "prefix".

**Comment by dshanske** [comment]
https://github.com/dshanske/indieweb-post-kinds/blob/trunk/includes/class-kind-plugins.php#L57

**Comment by dshanske** [comment]
X as experience is proposed here http://tantek.pbworks.com/w/page/21743973/Whistle

**Comment by pfefferle** [comment]
With "supported "prefix"" I meant supported by hum-core :)

So maybe it is an issue with the post-kinds plugin @dshanske ?

**Comment by bekopharm** [comment]
I wasn't aware that there are supported prefixes.

It's of the post-kinds type "Playing".

I'm also somewhat puzzled how this may be a post-kinds issue. I mean if hum can't deal with this why is it generated|allowed like this in the first place?

Checked with other post-kinds of the type "Playing" and they all seem to be broken. Same for "Listens".

Doesn't this affect _all_ IndieWeb plugin users that went with the recommended set of plugins?

**Comment by willnorris** [comment]
Are these using the officially supported way of doing custom post types where they are stored in the main posts table?  If so, then the same /b/NNN shorturls **should** still work, since they just have normal post IDs.  If the plugin is doing something different for the custom post types (like making a custom db table), then it would require a bit more work.

**Comment by dshanske** [comment]
No, all standard post type, just custom taxonomy

**Comment by pfefferle** [comment]
It is weird... I checked some short URLs for `kind/listen` and the `/x/XXX` links do not work, but if I replace them with `/b/XXX` they do.

**Comment by pfefferle** [comment]
@bekopharm can you re-create the rewrite-rules and re-check? (go to the permalinks and press the save button. you do not have to change something).

**Comment by willnorris** [comment]
I don't have a working WordPress install myself, but can someone try adding log statements to verify that `/x/NNN` URLs are actually being passed to hum?  I'm wondering if there is something elsewhere in WordPress that is handling that URL before hum gets it.

**Comment by willnorris** [comment]
right, I saw that.  But I'm wondering if our rewrite rules are conflicting with others.  Hence the check to see if `/x/NNN` is even making it to https://github.com/willnorris/wordpress-hum/blob/master/hum.php#L108

**Comment by pfefferle** [comment]
I think I found issue: The filter of the IndieWeb Post Kinds that adds the custom types is called too late. The easiest way to fix it, is to load the Post Kinds plugin earlier:

```php
add_action( 'init', array( 'Kind_' . $load, 'init' ), 9 );
```

**Comment by pfefferle** [comment]
I proposed a fix, can you review the change @bekopharm and/or @dshanske ? https://github.com/willnorris/wordpress-hum/pull/35

**Comment by bekopharm** [comment]
> right, I saw that. But I'm wondering if our rewrite rules are conflicting with others. Hence the check to see if `/x/NNN` is even making it to https://github.com/willnorris/wordpress-hum/blob/master/hum.php#L108

It doesn't make it to that line. Added a `die;` but it still run straight into the 404.

**Comment by bekopharm** [comment]
Can confirm that this is fixed [for me] with `af42f33d09ac990dafdd651287c8ec6a5428f0bd` of #35 

No idea what changed exactly since the last test but it does work now.

**Comment by StarrWulfe** [comment]
I’m experiencing this issue right now on a 2-week-old install with the latest wordpress 6.1.1, indieweb and hum 1.3.0 plugins.

Example:

  * Post: [https://starrwulfe.xyz/makanai-cooking-for-maikosan/](https://starrwulfe.xyz/makanai-cooking-for-maikosan/)
  * Hum produced this shortlink: [https://starrwulfe.xyz/x/1o2](https://starrwulfe.xyz/x/1o2)
  * If I manually change “x” to “b” I get [https://starrwulfe.xyz/b/1o2](https://starrwulfe.xyz/b/1o2)



How do I make Hum load last if that helps the fix…is it easier for me to just make a filter for ‘x’ and it’ll magically work
-or-
is there a UI to fix this manually that I’m missing?

(I could swear this had been working before and something changed to break it…)

(Originally published at: https://starrwulfe.xyz/t/1ve)

**Comment by pfefferle** [comment]
HUM was not updated for quite some time, can you check if there was a post kinda update lately?

/cc @dshanske ?

**Comment by dshanske** [comment]
Hasn't been, haven't touched the hum code in the interval, but happy to experiment

**Comment by StarrWulfe** [comment]
I concur. It's been doing it for me since the beginning and only with the "/x/" extension that seems to come up whenever the post kind is "experience" based like watch, craft,jam, etc.

**Comment by StarrWulfe** [comment]
OK I mitigated it by adding the extra letters for the post kinds to the array needed to build the shortlink properly:

``` php
/**
	 * Get the short URL types that are handled locally by WordPress.
	 *
	 * @uses apply_filters() Calls 'hum_local_types' with array of local types
	 *
	 * @return array local types
	 */
	public function local_types() {
		$local_types = array( 'b', 't', 'a', 'p', 'f', 'x', 'v' );
		return apply_filters( 'hum_local_types', $local_types );
	}
```

@dshanske are there any more I need to add? Where is Hum getting those shortlink classes from-- Post Kinds?
