### ISSUE TITLE
Link doesn't work?

### ISSUE THREAD

**Issue by YuriGal** [willnorris/wordpress-hum#36]
Not sure what I am doing wrong, but it doesn't seem to work for me. E.g. for post https://codecorner.galanter.net/2019/09/08/dynamic-linq-to-xml Hum produced link https://codecorner.galanter.net/b/zv, but it leads nowhere. Any idea how to fix it? Thanks!

**Comment by pfefferle** [comment]
I just checked the links you posted and it worked for me!

**Comment by YuriGal** [comment]
Huh, it does work now, thanks! Does it take a while for shortlink to take effect for some reason? I was getting 404 on it initially. Great shortener, by the way!

**Comment by pfefferle** [comment]
> Huh, it does work now, thanks! Does it take a while for shortlink to take effect for some reason? I was getting 404 on it initially.

Normally not 😳 maybe a caching thing?

> Great shortener, by the way!

All fame on @willnorris 😍

**Comment by pfefferle** [comment]
I will close this for now, please re-open if still an issue!
