### ISSUE TITLE
Custom Prefix causes error

### ISSUE THREAD

**Issue by regenpfeifer** [willnorris/wordpress-hum#37]
Hello,

I tried to define a custom prefix for hum, as it is described in the documentation:

```
add_filter('hum_redirect_base_e',
create_function('', 'return "https://ebird.org";'));

```
Unfortunately, this causes an error as `create_function` is deprecated.

Is there any other way to define a custom prefix?

Cf.: [WordPress Support](https://wordpress.org/support/topic/custom-prefix-causes-error/)

**Comment by pfefferle** [comment]
As @willnorris mentioned in your other issue, a possible solution is with an anonymous function: 

```PHP
add_filter( 'hum_redirect_base_e', function($url, $path) {
    return "https://ebird.org";
}, 11, 2 );
```

or the classic way:

```PHP
function custom_redirect_base_e( $url, $path ) {
    return "https://ebird.org";
}

add_filter( 'hum_redirect_base_e', 'custom_redirect_base_e', 11, 2 );
```

**Comment by regenpfeifer** [comment]
Thank you @pfefferle,

unfortunately the proposed functions don't seem tot work (contrary to the analogous redefining of the i-prefix for ISBN-search). I have tried these methods:

# method 1
```
add_filter( 'hum_redirect_base_e', function($url, $path) {
    return "https://ebird.org/" . $path;
}, 9, 2 );

```
# method 2
```
add_filter( 'hum_redirect_base_e', function($url, $path) {
   return "https://ebird.org";
}, 9, 2 );

```
# method 3
```
function custom_redirect_base_e( $url, $path ) {
    return "https://ebird.org";
}
add_filter( 'hum_redirect_base_e', 'custom_redirect_base_e', 9, 2 );


```None of these methods brings me outside of my blog to the intended extrernal site.

**Comment by pfefferle** [comment]
Can you change the priority (9) to something higher, like for example `15` and re-try it?

**Comment by willnorris** [comment]
`redirect_types` in your snippet above never gets called.  You can make it an anonymous function as well...

``` php
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    return $types;
});
```

And it looks like you should be able to use public functions withe code snippets plugin.  At least they [show an example of that here](https://ps.w.org/code-snippets/assets/screenshot-3.png?rev=2256244).

**Comment by regenpfeifer** [comment]
Thank you very much, @willnorris,

I now have the following code inserted as snippet:

```
# Define redirect types
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    return $types;
}, 15, 2 );

# eBird
add_filter( 'hum_redirect_base_e', function($url, $path) {
    return "https://ebird.org/" . $path;
}, 15, 2 );
```

I am sorry, but this lines also don't work. I am still getting redirected to my blog, not to the external site.

Unfortunately, I am everything else than a PHP expert. So it seems, that I have to give up at this stage. I have managed to adapt the `i` custom prefix, which has already been defined in the code of the plugin. But obviously I can't create a new custom prefix. I will wait until the plugin gets updated in the future.

**Comment by willnorris** [comment]
I don't have a working WordPress install anymore, so can't easily test this myself, so maybe Matthias can spot the error above.

One thing to note is that you modified the "hub_redirect_types" filter slightly from what I wrote.... you have it specified as taking two parameters, whereas it only takes one.  I don't recall how much of a problem that causes in WordPress.  The priority 15 shouldn't matter either way.

It's also worth noting that there is nothing to be updated in the plugin in the future (as far as this specific problem is concerned).  All of the hooks are there, it's just get them connected properly.

**Comment by regenpfeifer** [comment]
Thank you again, @willnorris,

I have now corrected the lines according to your original suggestion:

```
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    return $types;
});
```

This does change nothing, unfortunately. I understand that the plugin won't be updated in the future. But maybe at least the documentation should be corrected concerning the custom prefixes, because there is still an example there using deprecated WordPress functions which are causing an error.

**Comment by willnorris** [comment]
Okay, I figured it out.  I did a clean local install of WordPress with only the hum and code snippets plugin.  The bug is that you're using the `hum_redirect_base_e` filter rather than `hum_redirect_e`.  The `hum_redirect_base_*` is for when you want to redirect all requests for a given base to a specific URL, without including the path at all.  It only takes a single parameter, not two, which is causing a PHP error.  Instead, you want:

```php
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    return $types;
});

add_filter( 'hum_redirect_e', function($url, $path) {
    return "https://ebird.org/" . $path;
}, 15, 2);
```

that now works:

``` sh
% curl -i http://localhost:8080/wordpress/e/foo
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=UTF-8
Location: https://ebird.org/foo
Server: Caddy
Status: 301 Moved Permanently
X-Powered-By: PHP/8.2.3
X-Redirect-By: WordPress
Date: Tue, 04 Apr 2023 18:57:34 GMT
Content-Length: 0
```

And I apologize... I didn't mean that the plugin won't ever be updated in the future, just that I didn't think there was an update necessary to resolve this.  But you're right about the code sample using deprecated functions, and I'll fix that.

**Comment by willnorris** [comment]
oh, actually.... you could use `hum_redirect_base_e`... hum automatically appends the remaining path.  I forgot about that.  So this would also work (and would be equivalent):

``` php
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    return $types;
});

add_filter( 'hum_redirect_base_e', function() {
    return "https://ebird.org/";
});
```

**Comment by regenpfeifer** [comment]
@willnorris, thank you very much for all your efforts! Now the code is working and redirects to the external site. This is really great.

Just one last question, hopefully... I am now trying to configure several external redirections with different custom prefixes and have added this code to my snippet:

```
# eBird
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    return $types;
});

add_filter( 'hum_redirect_base_e', function() {
    return "https://ebird.org/";
});

# iNaturalist
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'n';
    return $types;
});

add_filter( 'hum_redirect_base_n', function() {
    return "https://www.inaturalist.org/";
});

# ISBN
add_filter( 'hum_redirect_i', function($url, $path) {
    return "https://www.worldcat.org/de/search?q=" . $path;
}, 9, 2 );
```

For the first redirection, eBird, with custom prefix `e` everything works fine, whereas for the second redirection, iNaturalist, with custom prefix `n` I am facing the same problem as before: the custom link is redirected to my blog instead of the external site.

Do I have to define **all custom prefixes at once** in order to get it working?

Thank you so much!

**Comment by pfefferle** [comment]
You do not have to add two filters to add support for 'n' and 'e', this should also work:

```PHP
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    $types[] = 'n';
    return $types;
});

add_filter( 'hum_redirect_base_e', function() {
    return "https://ebird.org/";
});

add_filter( 'hum_redirect_base_n', function() {
    return "https://www.inaturalist.org/";
});

# ISBN
add_filter( 'hum_redirect_i', function($url, $path) {
    return "https://www.worldcat.org/de/search?q=" . $path;
}, 9, 2 );
```

**Comment by regenpfeifer** [comment]
Thank you @willnorris and @pfefferle for your hints and please excuse me for answering so late.

I have now configured these filters for hum, and everything works perfect!

```
add_filter( 'hum_redirect_types', function($types) {
    $types[] = 'e';
    $types[] = 'u';
    return $types;
});

add_filter( 'hum_redirect_base_e', function() {
    return "https://ebird.org/";
});

add_filter( 'hum_redirect_base_u', function() {
    return "https://www.inaturalist.org/";
});

# ISBN
add_filter( 'hum_redirect_i', function($url, $path) {
    return "https://www.worldcat.org/de/search?q=" . $path;
}, 9, 2 );

```

I am adding one more question: Is it possible to **add sub-prefixes for custom links**, as with the built-in `.../i/a/`-links for isbn-amazon redirections? So I could configure links in the following way: `.../e/c/` redirecting to https://ebird.org/checklists

Thank you very much!

**Comment by pfefferle** [comment]
You can do that in your code, as we do it with `/i`:

https://github.com/willnorris/wordpress-hum/blob/master/hum.php#L226
