### ISSUE TITLE
Alternative to Amazon

### ISSUE THREAD

**Issue by regenpfeifer** [willnorris/wordpress-hum#38]
Hum redirects URLs with the `i` or `a` prefix automatically to amazon.com.

I think it would be appropriate to give the possibility to define an alternative, non-commercial service for retrieving ISBN data.

Cf.: [WordPress Support](https://wordpress.org/support/topic/alternative-to-amazon/)

**Comment by willnorris** [comment]
you can do so with the `hum_redirect_i` filter and any priority lower than 10.  You can see the default hook as an example [here](https://github.com/willnorris/wordpress-hum/blob/a83f3e8416ebc017caad30068182f87d32a4095a/hum.php#LL38C3-L38C79).

So (if my PHP and WordPress memory serves correctly) that would be something like:

```php
add_filter( 'hum_redirect_i', function($url, $path) {
    return "https://non-commerical-isbn-data-service/" . $path;
}, 9, 2 );
```

**Comment by regenpfeifer** [comment]
Thank you, @willnorris and @pfefferle,

this seems to work as intended. I am using the worldcat.org-Service and have added this code to my WordPress installation:

```
# ISBN
add_filter( 'hum_redirect_i', function($url, $path) {
    return "https://www.worldcat.org/de/search?q=" . $path;
}, 9, 2 );

```

**Comment by pfefferle** [comment]
I will close this issue then, please re-open it, if you have still issues.
