### ISSUE TITLE
Rewrite rules not flushed when adding custom types to custom plugin

### ISSUE THREAD

**Issue by jimkleiber** [willnorris/wordpress-hum#40]
I have been trying to add custom types and it was working when I had a custom redirect to something like `q` under `i/q/` but not when I was adding it just as `/q/`.

I found that the rewrite rules weren't being flushed when I updated my custom plugin, only when I activated/deactivated the hum plugin. Once I did that, my custom types were working properly.

Maybe a dumb question, but any suggestions on how I can call the `flush_rewrite_rules` method from my custom plugin?

**Comment by pfefferle** [comment]
We use the `register_activation_hook` for that https://github.com/willnorris/wordpress-hum/blob/3dd7e5db821ba05d834498dc5855a7ed6e1e0b34/hum.php#L21
